# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UIFMDB_19' do
pod 'MBProgressHUD', '~> 0.9.2'
pod 'FMDB', '~> 2.6.2'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UIFMDB_19

  target 'UIFMDB_19Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIFMDB_19UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
